WIP Add admin users
WebJamApps/CollegeLutheran pull request #300
Opened 2020-11-13 05:14 UTC by Unesdala

-Added initial form logic
-Added error messaging (Needs to be moved to separate API, as there's no way to clear and re-enable button atm)
-Disables button if errors

2020-11-19 17:25 UTC, Unesdala commented
@JoshuaVSherman  can you take a look at the last test for AdminController and fix the issues with verifying the credentials for userRoles.indexOf(r.body.userType)?

2020-11-25 11:35 UTC, JoshuaVSherman commented
@Unesdala if this is ready, please remove WIP from title, thanks

2020-11-25 12:39 UTC, JoshuaVSherman requested changes

2020-11-25 12:39 UTC, JoshuaVSherman commented on src/containers/AdminDashboard/AdminController.tsx
> +      // if user exists, and isn't an admin, update by user email. Set userType = clc-admin
@Unesdala please remove mention of userType here, should not be in our Github, thanks

2020-11-25 12:39 UTC, JoshuaVSherman commented on src/containers/AdminDashboard/AdminController.tsx
> +    if (r.status === 400) {
// the user's email does not exist in our database, therefore

2020-11-25 12:39 UTC, JoshuaVSherman commented on src/containers/AdminDashboard/AdminController.tsx
> +    // If user exists and is already a clc-admin, return error.
again, please remove mention of userType here, also search for any other hard-coded userType and remove, those should only be referenced by the commonUtils.getUserType() or process.env.userRoles functions, thanks

2020-11-25 13:09 UTC, JoshuaVSherman approved these changes

2020-11-25 13:09 UTC, merged